Getting started & creating a component documentation
ebi-webcomponents/nightingale pull request #252
Opened 2023-04-05 10:34 UTC by dlrice

- Created getting started doc which uses Sandpack to show demo code.
- Created creating a component

2023-04-06 08:23 UTC, gustavo-salazar requested changes
Nice job!
I added a few minor suggestions/comments in both tutorials, but I think in general they are what we are looking for.

2023-04-06 08:23 UTC, gustavo-salazar commented on stories/002.CreatingAComponent.stories.mdx
> +   2. The above example inherits from [LitElement](https://lit.dev/docs/api/LitElement/), while there is a base element for any Nightingale component named `NightingaleElement`.
I think is worth splitting this in 2 points:
2. Use `NightingaleElement` instead of `LitElement`...
3. Use of mixins, maybe adding one at a time.

2023-04-11 08:07 UTC, dlrice commented
@gustavo-salazar addressed all of the getting started comments.  In the end I had a refactor to try make it flow a bit better.

2023-04-11 11:08 UTC, gustavo-salazar approved these changes

2023-04-11 11:08 UTC, merged